// Auto-generated by Zodra — DO NOT EDIT

import { z } from 'zod';
export const CustomerSummarySchema = z.object({
  id: z.uuid(),
  name: z.string(),
  email: z.string(),
});

export interface CustomerSummary {
  id: string;
  name: string;
  email: string;
}
