// Auto-generated by Zodra — DO NOT EDIT

import { z } from 'zod';
export const DashboardOverviewSchema = z.object({
  totalOrders: z.number().int(),
  totalRevenue: z.number(),
  averageOrderValue: z.number(),
  activeCustomers: z.number().int(),
  lowStockProducts: z.number().int(),
}).describe('Aggregate order and inventory metrics');

/** Aggregate order and inventory metrics */
export interface DashboardOverview {
  totalOrders: number;
  totalRevenue: number;
  averageOrderValue: number;
  activeCustomers: number;
  lowStockProducts: number;
}
