// Auto-generated by Zodra — DO NOT EDIT

import { z } from 'zod';
import { ProductSchema } from './product';
import type { Product } from './product';

export const LineItemSchema = z.object({
  id: z.uuid(),
  product: ProductSchema,
  quantity: z.number().int().min(1),
  unitPrice: z.number(),
  totalPrice: z.number(),
});

export interface LineItem {
  id: string;
  product: Product;
  quantity: number;
  unitPrice: number;
  totalPrice: number;
}
