// Auto-generated by Zodra — DO NOT EDIT

import { z } from 'zod';
export const OrderItemInputSchema = z.object({
  productId: z.uuid(),
  quantity: z.number().int().min(1),
});

export interface OrderItemInput {
  productId: string;
  quantity: number;
}
