// Auto-generated by Zodra — DO NOT EDIT

import { z } from 'zod';
import { OrderItemInputSchema } from './order-item-input';
import type { OrderItemInput } from './order-item-input';

export const OrderInputSchema = z.object({
  customerId: z.uuid(),
  shippingAddress: z.string().optional(),
  items: z.array(OrderItemInputSchema),
});

export interface OrderInput {
  customerId: string;
  shippingAddress?: string;
  items: OrderItemInput[];
}
