// Auto-generated by Zodra — DO NOT EDIT

import { z } from 'zod';
import { OrderStatusSchema } from './order-status';
import type { OrderStatus } from './order-status';
import { CustomerSchema } from './customer';
import type { Customer } from './customer';
import { LineItemSchema } from './line-item';
import type { LineItem } from './line-item';
import { PaymentMethodSchema } from './payment-method';
import type { PaymentMethod } from './payment-method';

export const OrderSchema = z.object({
  id: z.uuid(),
  number: z.string(),
  status: OrderStatusSchema,
  customer: CustomerSchema,
  lineItems: z.array(LineItemSchema),
  paymentMethod: PaymentMethodSchema,
  totalAmount: z.number(),
  shippingAddress: z.string().optional(),
  estimatedDelivery: z.iso.date().nullable(),
  createdAt: z.iso.datetime(),
  updatedAt: z.iso.datetime(),
});

export interface Order {
  id: string;
  number: string;
  status: OrderStatus;
  customer: Customer;
  lineItems: LineItem[];
  paymentMethod: PaymentMethod;
  totalAmount: number;
  shippingAddress?: string;
  estimatedDelivery: null | string;
  createdAt: string;
  updatedAt: string;
}
