// Auto-generated by Zodra — DO NOT EDIT

import { z } from 'zod';
export const OrderStatusSchema = z.enum(['draft', 'confirmed', 'shipped', 'delivered', 'cancelled']);

export type OrderStatus = 'draft' | 'confirmed' | 'shipped' | 'delivered' | 'cancelled';
