// Auto-generated by Zodra — DO NOT EDIT

import { z } from 'zod';
export const PaymentMethodSchema = z.discriminatedUnion('type', [
  z.object({ type: z.literal('card'), lastFour: z.string().min(4).max(4), brand: z.string(), expiryMonth: z.string().min(2).max(2), expiryYear: z.string().min(4).max(4) }),
  z.object({ type: z.literal('bank_transfer'), bankName: z.string(), accountLastFour: z.string().min(4).max(4) }),
]);

export type PaymentMethod =
  | { type: 'card'; lastFour: string; brand: string; expiryMonth: string; expiryYear: string }
  | { type: 'bank_transfer'; bankName: string; accountLastFour: string };
