// Auto-generated by Zodra — DO NOT EDIT

import { z } from 'zod';
export const ProductSchema = z.object({
  id: z.uuid(),
  name: z.string(),
  sku: z.string(),
  price: z.number(),
  stock: z.number().int(),
  published: z.boolean(),
});

export interface Product {
  id: string;
  name: string;
  sku: string;
  price: number;
  stock: number;
  published: boolean;
}
