// Auto-generated by Zodra — DO NOT EDIT

import { z } from 'zod';
export const RevenueBreakdownSchema = z.object({
  status: z.string(),
  total: z.number(),
  count: z.number().int(),
}).describe('Revenue aggregated by order status');

/** Revenue aggregated by order status */
export interface RevenueBreakdown {
  status: string;
  total: number;
  count: number;
}
