// Auto-generated by Zodra — DO NOT EDIT

import { z } from 'zod';
export const TopProductSchema = z.object({
  name: z.string(),
  sku: z.string(),
  unitsSold: z.number().int(),
  revenue: z.number(),
}).describe('Product ranked by revenue');

/** Product ranked by revenue */
export interface TopProduct {
  name: string;
  sku: string;
  unitsSold: number;
  revenue: number;
}
