// Auto-generated by Zodra — DO NOT EDIT

import { z } from 'zod';
import { CustomerSummarySchema } from '../types/customer-summary';
import type { CustomerSummary } from '../types/customer-summary';
import { CustomerSchema } from '../types/customer';
import type { Customer } from '../types/customer';

export const IndexCustomersParamsSchema = z.object({

});

export const ShowCustomersParamsSchema = z.object({
  id: z.uuid(),
});

export const CreateCustomersParamsSchema = z.object({
  name: z.string(),
  email: z.string().describe('Primary contact email'),
  phone: z.string().optional(),
  notes: z.string().nullable(),
});

export const UpdateCustomersParamsSchema = z.object({
  name: z.string().optional(),
  email: z.string().optional().describe('Primary contact email'),
  phone: z.string().optional(),
  notes: z.string().nullable().optional(),
});

export const DestroyCustomersParamsSchema = z.object({
  id: z.uuid(),
});

export const CustomersContract = {
  index: { method: 'GET' as const, path: '/customers' as const, params: IndexCustomersParamsSchema, response: CustomerSummarySchema, collection: true as const },
  show: { method: 'GET' as const, path: '/customers/:id' as const, params: ShowCustomersParamsSchema, response: CustomerSchema },
  create: { method: 'POST' as const, path: '/customers' as const, params: CreateCustomersParamsSchema, response: CustomerSchema },
  update: { method: 'PATCH' as const, path: '/customers/:id' as const, params: UpdateCustomersParamsSchema, response: CustomerSchema },
  destroy: { method: 'DELETE' as const, path: '/customers/:id' as const, params: DestroyCustomersParamsSchema },
} as const;

export interface IndexCustomersParams {

}

export interface ShowCustomersParams {
  id: string;
}

export interface CreateCustomersParams {
  name: string;
  /** Primary contact email */
  email: string;
  phone?: string;
  notes: null | string;
}

export interface UpdateCustomersParams {
  name?: string;
  /** Primary contact email */
  email?: string;
  phone?: string;
  notes?: null | string;
}

export interface DestroyCustomersParams {
  id: string;
}

export interface CustomersContract {
  index: { method: 'GET'; path: '/customers'; params: IndexCustomersParams; response: CustomerSummary; collection: true };
  show: { method: 'GET'; path: '/customers/:id'; params: ShowCustomersParams; response: Customer };
  create: { method: 'POST'; path: '/customers'; params: CreateCustomersParams; response: Customer };
  update: { method: 'PATCH'; path: '/customers/:id'; params: UpdateCustomersParams; response: Customer };
  destroy: { method: 'DELETE'; path: '/customers/:id'; params: DestroyCustomersParams };
}
