// Auto-generated by Zodra — DO NOT EDIT

import { z } from 'zod';
import { DashboardOverviewSchema } from '../types/dashboard-overview';
import type { DashboardOverview } from '../types/dashboard-overview';
import { RevenueBreakdownSchema } from '../types/revenue-breakdown';
import type { RevenueBreakdown } from '../types/revenue-breakdown';
import { TopProductSchema } from '../types/top-product';
import type { TopProduct } from '../types/top-product';

export const ShowDashboardParamsSchema = z.object({

});

export const ShowDashboardResponseSchema = z.object({
  overview: DashboardOverviewSchema,
  revenueByStatus: z.array(RevenueBreakdownSchema),
  topProducts: z.array(TopProductSchema),
});

export const DashboardContract = {
  show: { method: 'GET' as const, path: '/dashboard' as const, params: ShowDashboardParamsSchema, response: ShowDashboardResponseSchema },
} as const;

export interface ShowDashboardParams {

}

export interface ShowDashboardResponse {
  overview: DashboardOverview;
  revenueByStatus: RevenueBreakdown[];
  topProducts: TopProduct[];
}

export interface DashboardContract {
  show: { method: 'GET'; path: '/dashboard'; params: ShowDashboardParams; response: ShowDashboardResponse };
}
