// Auto-generated by Zodra — DO NOT EDIT

import { ProductsContract } from './products';
import { CustomersContract } from './customers';
import { OrdersContract } from './orders';
import { SettingsContract } from './settings';

export const contracts = {
  products: ProductsContract,
  customers: CustomersContract,
  orders: OrdersContract,
  settings: SettingsContract,
} as const;

export const baseUrl = '/api/v1';
export * from './products';
export * from './customers';
export * from './orders';
export * from './settings';
