// Auto-generated by Zodra — DO NOT EDIT

import { z } from 'zod';

export const ShowInternalMetricsParamsSchema = z.object({

});

export const ShowInternalMetricsResponseSchema = z.object({
  totalOrders: z.number().int(),
  totalRevenue: z.number().int(),
  activeCustomers: z.number().int(),
});

export const InternalMetricsContract = {
  show: { method: 'GET' as const, path: '/internal_metrics' as const, params: ShowInternalMetricsParamsSchema, response: ShowInternalMetricsResponseSchema },
} as const;

export interface ShowInternalMetricsParams {

}

export interface ShowInternalMetricsResponse {
  totalOrders: number;
  totalRevenue: number;
  activeCustomers: number;
}

export interface InternalMetricsContract {
  show: { method: 'GET'; path: '/internal_metrics'; params: ShowInternalMetricsParams; response: ShowInternalMetricsResponse };
}
