// Auto-generated by Zodra — DO NOT EDIT

import { z } from 'zod';
import { OrderSchema } from '../types/order';
import type { Order } from '../types/order';
import { OrderItemInputSchema } from '../types/order-item-input';
import type { OrderItemInput } from '../types/order-item-input';
import { OrderStatusSchema } from '../types/order-status';
import type { OrderStatus } from '../types/order-status';

export const IndexOrdersParamsSchema = z.object({

});

export const ShowOrdersParamsSchema = z.object({
  id: z.uuid(),
});

export const CreateOrdersParamsSchema = z.object({
  customerId: z.uuid(),
  shippingAddress: z.string().optional(),
  items: z.array(OrderItemInputSchema),
});

export const ConfirmOrdersParamsSchema = z.object({
  id: z.uuid(),
});

export const CancelOrdersParamsSchema = z.object({
  id: z.uuid(),
});

export const SearchOrdersParamsSchema = z.object({
  status: OrderStatusSchema.optional(),
  fromDate: z.iso.date().optional(),
  toDate: z.iso.date().optional(),
});

export type CreateOrdersBusinessError = { code: 'validation_failed'; message: string };

export type ConfirmOrdersBusinessError = { code: 'not_found' | 'invalid_transition'; message: string };

export type CancelOrdersBusinessError = { code: 'not_found' | 'invalid_transition'; message: string };

export const OrdersContract = {
  index: { method: 'GET' as const, path: '/orders' as const, params: IndexOrdersParamsSchema, response: OrderSchema, collection: true as const },
  show: { method: 'GET' as const, path: '/orders/:id' as const, params: ShowOrdersParamsSchema, response: OrderSchema },
  create: { method: 'POST' as const, path: '/orders' as const, params: CreateOrdersParamsSchema, response: OrderSchema, errors: [{ code: 'validation_failed' as const, status: 422 as const }] as const },
  confirm: { method: 'PATCH' as const, path: '/orders/:id/confirm' as const, params: ConfirmOrdersParamsSchema, response: OrderSchema, errors: [{ code: 'not_found' as const, status: 404 as const }, { code: 'invalid_transition' as const, status: 422 as const }] as const },
  cancel: { method: 'PATCH' as const, path: '/orders/:id/cancel' as const, params: CancelOrdersParamsSchema, response: OrderSchema, errors: [{ code: 'not_found' as const, status: 404 as const }, { code: 'invalid_transition' as const, status: 422 as const }] as const },
  search: { method: 'GET' as const, path: '/orders/search' as const, params: SearchOrdersParamsSchema, response: OrderSchema, collection: true as const },
} as const;

export interface IndexOrdersParams {

}

export interface ShowOrdersParams {
  id: string;
}

export interface CreateOrdersParams {
  customerId: string;
  shippingAddress?: string;
  items: OrderItemInput[];
}

export interface ConfirmOrdersParams {
  id: string;
}

export interface CancelOrdersParams {
  id: string;
}

export interface SearchOrdersParams {
  status?: OrderStatus;
  fromDate?: string;
  toDate?: string;
}

export interface OrdersContract {
  index: { method: 'GET'; path: '/orders'; params: IndexOrdersParams; response: Order; collection: true };
  show: { method: 'GET'; path: '/orders/:id'; params: ShowOrdersParams; response: Order };
  create: { method: 'POST'; path: '/orders'; params: CreateOrdersParams; response: Order };
  confirm: { method: 'PATCH'; path: '/orders/:id/confirm'; params: ConfirmOrdersParams; response: Order };
  cancel: { method: 'PATCH'; path: '/orders/:id/cancel'; params: CancelOrdersParams; response: Order };
  search: { method: 'GET'; path: '/orders/search'; params: SearchOrdersParams; response: Order; collection: true };
}
