// Auto-generated by Zodra — DO NOT EDIT

import { z } from 'zod';
import { ProductSchema } from '../types/product';
import type { Product } from '../types/product';

export const IndexProductsParamsSchema = z.object({

});

export const ShowProductsParamsSchema = z.object({
  id: z.uuid(),
});

export const CreateProductsParamsSchema = z.object({
  name: z.string().min(1),
  sku: z.string().min(1),
  price: z.number().min(0),
  stock: z.number().int().min(0),
  published: z.boolean().default(false),
});

export const UpdateProductsParamsSchema = z.object({
  id: z.uuid(),
  name: z.string().min(1).optional(),
  sku: z.string().min(1).optional(),
  price: z.number().min(0).optional(),
  stock: z.number().int().min(0).optional(),
  published: z.boolean().optional(),
});

export const DestroyProductsParamsSchema = z.object({
  id: z.uuid(),
});

export const ProductsContract = {
  index: { method: 'GET' as const, path: '/products' as const, params: IndexProductsParamsSchema, response: ProductSchema, collection: true as const },
  show: { method: 'GET' as const, path: '/products/:id' as const, params: ShowProductsParamsSchema, response: ProductSchema },
  create: { method: 'POST' as const, path: '/products' as const, params: CreateProductsParamsSchema, response: ProductSchema },
  update: { method: 'PATCH' as const, path: '/products/:id' as const, params: UpdateProductsParamsSchema, response: ProductSchema },
  destroy: { method: 'DELETE' as const, path: '/products/:id' as const, params: DestroyProductsParamsSchema },
} as const;

export interface IndexProductsParams {

}

export interface ShowProductsParams {
  id: string;
}

export interface CreateProductsParams {
  name: string;
  sku: string;
  price: number;
  stock: number;
  published: boolean;
}

export interface UpdateProductsParams {
  id: string;
  name?: string;
  sku?: string;
  price?: number;
  stock?: number;
  published?: boolean;
}

export interface DestroyProductsParams {
  id: string;
}

export interface ProductsContract {
  index: { method: 'GET'; path: '/products'; params: IndexProductsParams; response: Product; collection: true };
  show: { method: 'GET'; path: '/products/:id'; params: ShowProductsParams; response: Product };
  create: { method: 'POST'; path: '/products'; params: CreateProductsParams; response: Product };
  update: { method: 'PATCH'; path: '/products/:id'; params: UpdateProductsParams; response: Product };
  destroy: { method: 'DELETE'; path: '/products/:id'; params: DestroyProductsParams };
}
