// Auto-generated by Zodra — DO NOT EDIT

import { z } from 'zod';

export const ShowSettingsParamsSchema = z.object({

});

export const UpdateSettingsParamsSchema = z.object({
  storeName: z.string().min(1).optional(),
  currency: z.string().min(3).max(3).optional(),
  timezone: z.string().optional(),
  maintenanceMode: z.boolean().optional(),
});

export const ShowSettingsResponseSchema = z.object({
  storeName: z.string(),
  currency: z.string(),
  timezone: z.string(),
  maintenanceMode: z.boolean(),
});

export const UpdateSettingsResponseSchema = z.object({
  storeName: z.string(),
  currency: z.string(),
  timezone: z.string(),
  maintenanceMode: z.boolean(),
});

export const SettingsContract = {
  show: { method: 'GET' as const, path: '/settings' as const, params: ShowSettingsParamsSchema, response: ShowSettingsResponseSchema },
  update: { method: 'PATCH' as const, path: '/settings' as const, params: UpdateSettingsParamsSchema, response: UpdateSettingsResponseSchema },
} as const;

export interface ShowSettingsParams {

}

export interface UpdateSettingsParams {
  storeName?: string;
  currency?: string;
  timezone?: string;
  maintenanceMode?: boolean;
}

export interface ShowSettingsResponse {
  storeName: string;
  currency: string;
  timezone: string;
  maintenanceMode: boolean;
}

export interface UpdateSettingsResponse {
  storeName: string;
  currency: string;
  timezone: string;
  maintenanceMode: boolean;
}

export interface SettingsContract {
  show: { method: 'GET'; path: '/settings'; params: ShowSettingsParams; response: ShowSettingsResponse };
  update: { method: 'PATCH'; path: '/settings'; params: UpdateSettingsParams; response: UpdateSettingsResponse };
}
