// Auto-generated by Zodra — DO NOT EDIT

import { z } from 'zod';

export const ShowSettingsParamsSchema = z.object({

});

export const UpdateSettingsParamsSchema = z.object({
  storeName: z.string().min(1).optional(),
  currency: z.string().min(3).max(3).optional(),
  timezone: z.string().optional(),
  maintenanceMode: z.boolean().optional(),
});

export const SettingsContract = {
  show: { method: 'GET' as const, path: '/settings' as const, params: ShowSettingsParamsSchema },
  update: { method: 'PATCH' as const, path: '/settings' as const, params: UpdateSettingsParamsSchema },
} as const;

export interface ShowSettingsParams {

}

export interface UpdateSettingsParams {
  storeName?: string;
  currency?: string;
  timezone?: string;
  maintenanceMode?: boolean;
}

export interface SettingsContract {
  show: { method: 'GET'; path: '/settings'; params: ShowSettingsParams };
  update: { method: 'PATCH'; path: '/settings'; params: UpdateSettingsParams };
}
