"use client"

import { useState } from "react"
import { CodeBlock } from "@/components/code-block"
import { cn } from "@/lib/utils"

const tabs = [
  { id: "type", label: "Ruby type" },
  { id: "contract", label: "Contract" },
  { id: "schema", label: "Generated schema" },
  { id: "frontend", label: "Frontend usage" },
]

const codeExamples = {
  type: `Zodra.type :product do
  uuid :id
  string :name, min: 1, max: 255
  string? :description
  decimal :price, min: 0
  string :currency, enum: %w[USD EUR GBP]
  boolean :in_stock, default: true
  array :tags, of: :string
  timestamps
end`,

  contract: `Zodra.contract :products do
  action :create do
    params from: :product, omit: [:id] do
      string :sku, min: 1
    end
    response :product
  end

  action :index do
    response :product, collection: true
  end

  action :show do
    params { uuid :id }
    response :product
  end
end`,

  schema: `// Auto-generated by Zodra — DO NOT EDIT
import { z } from 'zod'

export const ProductSchema = z.object({
  id: z.string().uuid(),
  name: z.string().min(1).max(255),
  description: z.string().optional(),
  price: z.number().min(0),
  currency: z.enum(['USD', 'EUR', 'GBP']),
  in_stock: z.boolean().default(true),
  tags: z.array(z.string()),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
})

export type Product = z.infer<typeof ProductSchema>

export const CreateProductsParamsSchema = z.object({
  name: z.string().min(1).max(255),
  description: z.string().optional(),
  price: z.number().min(0),
  currency: z.enum(['USD', 'EUR', 'GBP']),
  in_stock: z.boolean().default(true),
  tags: z.array(z.string()),
  sku: z.string().min(1),
})`,

  frontend: `import { ProductSchema } from '@zodra/client'
import type { Product } from '@zodra/client'

// Type-safe API calls
async function createProduct(data: CreateProductsParams) {
  const validated = CreateProductsParamsSchema.parse(data)

  const response = await fetch('/api/v1/products', {
    method: 'POST',
    body: JSON.stringify(validated),
  })

  return ProductSchema.parse(await response.json())
}

// Full autocomplete in your IDE
const product = await createProduct({
  name: "Premium Widget",
  price: 29.99,
  currency: "USD",
  in_stock: true,
  tags: ["new", "featured"],
  sku: "PWG-001",
})`
}

export function CodeExample() {
  const [activeTab, setActiveTab] = useState<keyof typeof codeExamples>("type")

  const getLanguage = (tab: string) => {
    if (tab === "type" || tab === "contract") return "ruby"
    return "typescript"
  }

  const getFilename = (tab: string) => {
    switch (tab) {
      case "type": return "app/types/product.rb"
      case "contract": return "app/contracts/products.rb"
      case "schema": return "zodra/product.ts"
      case "frontend": return "src/api/products.ts"
      default: return ""
    }
  }

  return (
    <section className="py-24 px-6 lg:px-12">
      <div className="max-w-5xl mx-auto">
        <div className="text-center mb-12">
          <h2 className="text-3xl sm:text-4xl font-bold tracking-tight">
            See it in action
          </h2>
          <p className="mt-4 text-muted-foreground text-lg max-w-xl mx-auto">
            From Ruby type to type-safe frontend in seconds
          </p>
        </div>

        {/* Tab Switcher */}
        <div className="flex items-center justify-center mb-6">
          <div className="inline-flex rounded-lg bg-secondary/50 p-1">
            {tabs.map((tab) => (
              <button
                key={tab.id}
                onClick={() => setActiveTab(tab.id as keyof typeof codeExamples)}
                className={cn(
                  "px-4 py-2 text-sm font-medium rounded-md transition-all",
                  activeTab === tab.id
                    ? "bg-[#C9184A] text-white"
                    : "text-muted-foreground hover:text-foreground"
                )}
              >
                {tab.label}
              </button>
            ))}
          </div>
        </div>

        {/* Code Block */}
        <div className="rounded-xl border border-border overflow-hidden">
          <CodeBlock
            code={codeExamples[activeTab]}
            language={getLanguage(activeTab)}
            filename={getFilename(activeTab)}
            showLineNumbers
          />
        </div>
      </div>
    </section>
  )
}
