"use client"

import { useState } from "react"
import { DynamicCodeBlock } from "fumadocs-ui/components/dynamic-codeblock"
import { cn } from "@/lib/utils"

const tabs = [
  { id: "type", label: "Ruby type" },
  { id: "contract", label: "Contract" },
  { id: "schema", label: "Generated schema" },
  { id: "frontend", label: "Frontend usage" },
]

const codeExamples = {
  type: `Zodra.type :product do
  uuid :id
  string :name, min: 1, max: 255
  string? :description
  decimal :price, min: 0
  string :currency, enum: %w[USD EUR GBP]
  boolean :in_stock, default: true
  array :tags, of: :string
  timestamps
end`,

  contract: `Zodra.contract :products do
  action :create do
    params from: :product, omit: [:id] do
      string :sku, min: 1
    end
    response :product
  end

  action :index do
    response :product, collection: true
  end

  action :show do
    params { uuid :id }
    response :product
  end
end`,

  schema: `// Auto-generated by Zodra — DO NOT EDIT
import { z } from 'zod'

export const ProductSchema = z.object({
  id: z.string().uuid(),
  name: z.string().min(1).max(255),
  description: z.string().optional(),
  price: z.number().min(0),
  currency: z.enum(['USD', 'EUR', 'GBP']),
  in_stock: z.boolean().default(true),
  tags: z.array(z.string()),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
})

export type Product = z.infer<typeof ProductSchema>

export const CreateProductsParamsSchema = z.object({
  name: z.string().min(1).max(255),
  description: z.string().optional(),
  price: z.number().min(0),
  currency: z.enum(['USD', 'EUR', 'GBP']),
  in_stock: z.boolean().default(true),
  tags: z.array(z.string()),
  sku: z.string().min(1),
})`,

  frontend: `import { createApiClient } from '@zodra/client'
import { contracts } from './zodra/contracts'

// One-time setup — typed from generated schemas
const api = createApiClient({
  baseUrl: '/api/v1',
  contracts,
})

// Full type safety — params and response are inferred
const { data: product } = await api.products.create({
  name: "Premium Widget",
  price: 29.99,
  currency: "USD",
  in_stock: true,
  tags: ["new", "featured"],
  sku: "PWG-001",
})

// product is typed as Product
console.log(product.name, product.currency)`
}

type TabId = keyof typeof codeExamples

const tabLanguages: Record<TabId, string> = {
  type: "ruby",
  contract: "ruby",
  schema: "typescript",
  frontend: "typescript",
}

const tabFilenames: Record<TabId, string> = {
  type: "app/types/product.rb",
  contract: "app/contracts/products.rb",
  schema: "zodra/product.ts",
  frontend: "src/api/client.ts",
}

export function CodeExample() {
  const [activeTab, setActiveTab] = useState<TabId>("type")

  return (
    <section className="py-24 px-6 lg:px-12">
      <div className="max-w-5xl mx-auto">
        <div className="text-center mb-12">
          <h2 className="text-3xl sm:text-4xl font-bold tracking-tight">
            See it in action
          </h2>
          <p className="mt-4 text-muted-foreground text-lg max-w-xl mx-auto">
            From Ruby type to type-safe frontend in seconds
          </p>
        </div>

        {/* Tab Switcher */}
        <div className="flex items-center justify-center mb-6 overflow-x-auto">
          <div className="inline-flex rounded-lg bg-secondary/50 p-1">
            {tabs.map((tab) => (
              <button
                key={tab.id}
                onClick={() => setActiveTab(tab.id as TabId)}
                className={cn(
                  "px-4 py-2 text-sm font-medium rounded-md transition-all whitespace-nowrap",
                  activeTab === tab.id
                    ? "bg-brand text-white"
                    : "text-muted-foreground hover:text-foreground"
                )}
              >
                {tab.label}
              </button>
            ))}
          </div>
        </div>

        {/* Code Block */}
        <DynamicCodeBlock
          code={codeExamples[activeTab]}
          lang={tabLanguages[activeTab]}
          codeblock={{
            title: tabFilenames[activeTab],
            "data-line-numbers": true,
          }}
        />
      </div>
    </section>
  )
}
