import { DynamicCodeBlock } from "fumadocs-ui/components/dynamic-codeblock"

const step1Code = `# Define types in Ruby
Zodra.type :post do
  uuid :id
  string :title, min: 1
  string :body
  boolean :published, default: false
  timestamps
end`

const step2Code = `// Auto-generated by Zodra
import { z } from 'zod'

export const PostSchema = z.object({
  id: z.uuid(),
  title: z.string().min(1),
  body: z.string(),
  published: z.boolean().default(false),
  created_at: z.iso.datetime(),
  updated_at: z.iso.datetime(),
})`

const step3Code = `// Use in your frontend
import { createApiClient } from '@zodra/client'
import { contracts } from './zodra/contracts'

const api = createApiClient({
  baseUrl: '/api/v1',
  contracts,
})

const { data } = await api.posts.create({
  title: "Hello World",
  body: "My first post",
})`

const steps = [
  {
    number: 1,
    title: "Define in Ruby",
    description: "Use the Zodra DSL to define types, contracts, and API routes.",
    code: step1Code,
    lang: "ruby",
  },
  {
    number: 2,
    title: "Zodra Generates",
    description: "TypeScript types, Zod schemas, and a typed client from your Ruby definitions.",
    code: step2Code,
    lang: "typescript",
  },
  {
    number: 3,
    title: "Use in Frontend",
    description: "Import generated schemas with full TypeScript inference and runtime validation.",
    code: step3Code,
    lang: "typescript",
  },
] as const

export function HowItWorks() {
  return (
    <section className="py-12 sm:py-16 lg:py-24 px-4 sm:px-6 lg:px-12">
      <div className="max-w-6xl mx-auto">
        <div className="text-center mb-10 sm:mb-16">
          <h2 className="text-3xl sm:text-4xl font-bold tracking-tight">
            How it works
          </h2>
          <p className="mt-4 text-muted-foreground text-lg max-w-xl mx-auto">
            Three simple steps to type-safe bliss
          </p>
        </div>

        <div className="grid lg:grid-cols-3 gap-8">
          {steps.map((step) => (
            <div key={step.number} className="flex flex-col gap-4 min-w-0 overflow-hidden">
              <div className="flex items-center gap-3">
                <div className="flex items-center justify-center w-10 h-10 shrink-0 rounded-full bg-brand text-white font-bold">
                  {step.number}
                </div>
                <h3 className="text-xl font-semibold">{step.title}</h3>
              </div>
              <p className="text-muted-foreground">
                {step.description}
              </p>
              <div className="mt-auto flex-1 grid">
                <DynamicCodeBlock code={step.code} lang={step.lang} />
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  )
}
