# frozen_string_literal: true

require 'tmpdir'

RSpec.describe Zodra::Export::Writer do
  subject(:writer) { described_class.new(configuration) }

  let(:configuration) { Zodra::Configuration.new }
  let(:output_dir) { Dir.mktmpdir }

  before do
    Zodra::TypeRegistry.global.clear!
    Zodra::ContractRegistry.global.clear!
    Zodra::ApiRegistry.global.clear!
    configuration.output_path = output_dir
  end

  after do
    Zodra::TypeRegistry.global.clear!
    Zodra::ContractRegistry.global.clear!
    Zodra::ApiRegistry.global.clear!
    FileUtils.rm_rf(output_dir)
  end

  describe '#write_all' do
    it 'writes type files to types/ subdirectory' do
      Zodra.type :user do
        string :name
        integer :age
      end

      paths = writer.write_all

      type_path = File.join(output_dir, 'types', 'user.ts')
      expect(paths).to include(type_path)
      content = File.read(type_path)
      expect(content).to include('export const UserSchema = z.object({')
      expect(content).to include('export interface User {')
    end

    it 'writes types barrel' do
      Zodra.type :user do
        string :name
      end

      writer.write_all

      barrel = File.read(File.join(output_dir, 'types', 'index.ts'))
      expect(barrel).to include("export * from './user';")
    end

    it 'writes contract files to contracts/ subdirectory' do
      Zodra.type :user do
        uuid :id
        string :name
      end

      contract = Zodra.contract :users do
        action :index do
          params {}
          response :user
        end
      end

      contract.find_action(:index).tap do |a|
        a.http_method = :get
        a.path = '/users'
      end

      Zodra.api '/api/v1' do
        resources :users
      end

      paths = writer.write_all

      contract_path = File.join(output_dir, 'contracts', 'users.ts')
      expect(paths).to include(contract_path)
      content = File.read(contract_path)
      expect(content).to include('UsersContract')
    end

    it 'writes contracts barrel with baseUrl' do
      Zodra.type :user do
        uuid :id
        string :name
      end

      contract = Zodra.contract :users do
        action :index do
          params {}
          response :user
        end
      end

      contract.find_action(:index).tap do |a|
        a.http_method = :get
        a.path = '/users'
      end

      Zodra.api '/api/v1' do
        resources :users
      end

      writer.write_all

      barrel = File.read(File.join(output_dir, 'contracts', 'index.ts'))
      expect(barrel).to include('export const contracts = {')
      expect(barrel).to include("export const baseUrl = '/api/v1';")
    end

    it 'writes root barrel' do
      Zodra.type :user do
        string :name
      end

      writer.write_all

      barrel = File.read(File.join(output_dir, 'index.ts'))
      expect(barrel).to include("export * from './types';")
      expect(barrel).to include("export * from './contracts';")
    end

    it 'prepends auto-generated header to all files' do
      Zodra.type :user do
        string :name
      end

      writer.write_all

      content = File.read(File.join(output_dir, 'types', 'user.ts'))
      expect(content).to start_with("// Auto-generated by Zodra — DO NOT EDIT\n")
    end

    it 'creates output directories if missing' do
      nested_dir = File.join(output_dir, 'deep', 'nested')
      configuration.output_path = nested_dir

      Zodra.type :user do
        string :name
      end

      writer.write_all

      expect(File.exist?(File.join(nested_dir, 'types', 'user.ts'))).to be true
    end

    it 'cleans output directory before writing' do
      stale_file = File.join(output_dir, 'old_file.ts')
      FileUtils.mkdir_p(output_dir)
      File.write(stale_file, 'stale content')

      Zodra.type :user do
        string :name
      end

      writer.write_all

      expect(File.exist?(stale_file)).to be false
    end
  end
end
