# frozen_string_literal: true

module Zodra
  module Export
    class FileTreeBuilder
      include NamingConventions

      HEADER = "// Auto-generated by Zodra — DO NOT EDIT\n"

      def initialize(configuration)
        @key_format = configuration.key_format
        @zod_import = configuration.zod_import
        @zod_mapper = ZodMapper.new(key_format: @key_format)
        @ts_mapper = TypeScriptMapper.new(key_format: @key_format)
      end

      def build
        contracts = ContractRegistry.global.to_a
        api_definitions = ApiRegistry.global.to_a
        base_path = api_definitions.first&.base_path

        definitions = SurfaceResolver.call(TypeRegistry.global.to_a, contracts)
        analysis = TypeAnalysis.call(definitions)

        @definitions_by_name = analysis.sorted.to_h { |d| [d.name, d] }
        @cycles = analysis.cycles
        @dependency_graph = build_dependency_graph(analysis.sorted)

        files = {}
        build_type_files(analysis.sorted, files)
        build_contract_files(contracts, base_path, files)
        build_barrel(contracts, api_definitions, files)
        files
      end

      private

      def build_dependency_graph(definitions)
        definitions.to_h do |definition|
          deps = Set.new
          definition.attributes.each_value do |attr|
            dep = attr.dependency_name
            deps << dep if dep && @definitions_by_name.key?(dep)
          end
          definition.variants.each do |variant|
            variant.attributes.each_value do |attr|
              dep = attr.dependency_name
              deps << dep if dep && @definitions_by_name.key?(dep)
            end
          end
          [definition.name, deps]
        end
      end

      def build_type_files(sorted_definitions, files)
        sorted_definitions.each do |definition|
          path = "types/#{file_name(definition.name)}.ts"
          files[path] = build_type_file(definition)
        end

        files['types/index.ts'] = build_types_barrel(sorted_definitions)
      end

      def build_type_file(definition)
        deps = @dependency_graph[definition.name] || Set.new
        lazy = @cycles.include?(definition.name)

        parts = [HEADER]
        parts << "import { z } from '#{@zod_import}';"

        deps.each do |dep_name|
          dep_file = file_name(dep_name)
          schema_import = "#{pascal_case(dep_name)}Schema"
          type_import = pascal_case(dep_name)
          parts << "import { #{schema_import} } from './#{dep_file}';"
          parts << "import type { #{type_import} } from './#{dep_file}';"
        end

        parts << '' if deps.any?
        parts << @zod_mapper.map_definition(definition, lazy:)
        parts << ''
        parts << @ts_mapper.map_definition(definition)
        "#{parts.join("\n")}\n"
      end

      def build_types_barrel(definitions)
        lines = [HEADER]
        definitions.each do |definition|
          lines << "export * from './#{file_name(definition.name)}';"
        end
        "#{lines.join("\n")}\n"
      end

      def build_contract_files(contracts, base_path, files)
        contracts.each do |contract|
          path = "contracts/#{file_name(contract.name)}.ts"
          files[path] = build_contract_file(contract, base_path)
        end

        files['contracts/index.ts'] = build_contracts_barrel(contracts, base_path)
      end

      def build_contract_file(contract, base_path)
        type_deps = collect_contract_type_dependencies(contract)

        parts = [HEADER]
        parts << "import { z } from '#{@zod_import}';"

        type_deps.each do |dep_name|
          dep_file = file_name(dep_name)
          schema_import = "#{pascal_case(dep_name)}Schema"
          type_import = pascal_case(dep_name)
          parts << "import { #{schema_import} } from '../types/#{dep_file}';"
          parts << "import type { #{type_import} } from '../types/#{dep_file}';"
        end

        parts << ''
        parts << @zod_mapper.map_contract(contract, base_path:)
        parts << ''
        parts << @ts_mapper.map_contract(contract, base_path:)
        "#{parts.join("\n")}\n"
      end

      def collect_contract_type_dependencies(contract)
        deps = Set.new
        contract.actions.each_value do |action|
          deps << action.response_type if action.response_type && @definitions_by_name.key?(action.response_type)
          collect_definition_dependencies(action.params, deps)
          collect_definition_dependencies(action.response_definition, deps) if action.inline_response?
        end
        deps
      end

      def collect_definition_dependencies(definition, deps)
        definition.attributes.each_value do |attr|
          dep = attr.dependency_name
          deps << dep if dep && @definitions_by_name.key?(dep)
        end
      end

      def build_contracts_barrel(contracts, base_path)
        contract_names = resolve_contract_names(contracts)

        parts = [HEADER]

        contract_names.each do |name|
          parts << "import { #{pascal_case(name)}Contract } from './#{file_name(name)}';"
        end

        entries = contract_names.map do |name|
          "  #{camel_case(name)}: #{pascal_case(name)}Contract"
        end

        parts << ''
        parts << "export const contracts = {\n#{entries.join(",\n")},\n} as const;"

        if base_path
          parts << ''
          parts << "export const baseUrl = '#{base_path}';"
        end

        contract_names.each do |name|
          parts << "export * from './#{file_name(name)}';"
        end

        "#{parts.join("\n")}\n"
      end

      def build_barrel(_contracts, _api_definitions, files)
        parts = [HEADER]
        parts << "export * from './types';"
        parts << "export * from './contracts';"
        files['index.ts'] = "#{parts.join("\n")}\n"
      end

      def resolve_contract_names(contracts)
        api_definitions = ApiRegistry.global.to_a

        if api_definitions.any?
          names = []
          api_definitions.each do |api|
            api.resources.each { |resource| collect_resource_names(resource, names) }
          end
          names
        else
          contracts.map { |c| c.name.to_s }
        end
      end

      def collect_resource_names(resource, names)
        names << resource.contract_name.to_s
        resource.children.each { |child| collect_resource_names(child, names) }
      end
    end
  end
end
