# frozen_string_literal: true

require "fileutils"

module Zodra
  module Export
    class Writer
      HEADER = "// Auto-generated by Zodra — DO NOT EDIT"

      FORMATS = {
        zod: "schemas.ts",
        typescript: "types.ts"
      }.freeze

      def initialize(configuration)
        @configuration = configuration
      end

      def write(format)
        content = Export.generate(format,
                                 key_format: @configuration.key_format,
                                 zod_import: @configuration.zod_import)

        write_file(FORMATS.fetch(format), content)
      end

      def write_contracts
        content = Export.generate_contracts
        return if content.empty?

        write_file("contracts.ts", content)
      end

      def write_all
        paths = FORMATS.keys.map { |format| write(format) }
        contracts_path = write_contracts
        paths << contracts_path if contracts_path
        paths
      end

      private

      def write_file(filename, content)
        FileUtils.mkdir_p(@configuration.output_path)
        filepath = File.join(@configuration.output_path, filename)
        File.write(filepath, "#{HEADER}\n#{content}\n")
        filepath
      end
    end
  end
end
