// Auto-generated by Zodra — DO NOT EDIT
import { ProductsContract, CustomersContract, OrdersContract, SettingsContract } from './schemas';

export const contracts = {
  products: ProductsContract,
  customers: CustomersContract,
  orders: OrdersContract,
  settings: SettingsContract,
} as const;

export const baseUrl = '/api/v1';
