// Auto-generated by Zodra — DO NOT EDIT
import { z } from 'zod';

export const CustomerSchema = z.object({
  id: z.uuid(),
  name: z.string(),
  email: z.string(),
  phone: z.string().optional(),
  notes: z.string().nullable(),
  registeredAt: z.iso.datetime(),
  createdAt: z.iso.datetime(),
  updatedAt: z.iso.datetime(),
});

export const CustomerSummarySchema = z.object({
  id: z.uuid(),
  name: z.string(),
  email: z.string(),
});

export const OrderItemInputSchema = z.object({
  productId: z.uuid(),
  quantity: z.number().int().min(1),
});

export const OrderStatusSchema = z.enum(['draft', 'confirmed', 'shipped', 'delivered', 'cancelled']);

export const PaymentMethodSchema = z.discriminatedUnion('type', [
  z.object({ type: z.literal('card'), lastFour: z.string().min(4).max(4), brand: z.string(), expiryMonth: z.string().min(2).max(2), expiryYear: z.string().min(4).max(4) }),
  z.object({ type: z.literal('bank_transfer'), bankName: z.string(), accountLastFour: z.string().min(4).max(4) }),
]);

export const ProductSchema = z.object({
  id: z.uuid(),
  name: z.string(),
  sku: z.string(),
  price: z.number(),
  stock: z.number().int(),
  published: z.boolean(),
});

export const LineItemSchema = z.object({
  id: z.uuid(),
  product: ProductSchema,
  quantity: z.number().int().min(1),
  unitPrice: z.number(),
  totalPrice: z.number(),
});

export const OrderSchema = z.object({
  id: z.uuid(),
  number: z.string(),
  status: OrderStatusSchema,
  customer: CustomerSchema,
  lineItems: z.array(LineItemSchema),
  paymentMethod: PaymentMethodSchema,
  totalAmount: z.number(),
  shippingAddress: z.string().optional(),
  estimatedDelivery: z.iso.date().nullable(),
  createdAt: z.iso.datetime(),
  updatedAt: z.iso.datetime(),
});

export const IndexCustomersParamsSchema = z.object({

});

export const ShowCustomersParamsSchema = z.object({
  id: z.uuid(),
});

export const CreateCustomersParamsSchema = z.object({
  name: z.string(),
  email: z.string(),
  phone: z.string().optional(),
  notes: z.string().nullable(),
});

export const UpdateCustomersParamsSchema = z.object({
  name: z.string().optional(),
  email: z.string().optional(),
  phone: z.string().optional(),
  notes: z.string().nullable().optional(),
});

export const DestroyCustomersParamsSchema = z.object({
  id: z.uuid(),
});

export const CustomersContract = {
  index: { method: 'GET' as const, path: '/api/v1/customers' as const, params: IndexCustomersParamsSchema, response: CustomerSummarySchema },
  show: { method: 'GET' as const, path: '/api/v1/customers/:id' as const, params: ShowCustomersParamsSchema, response: CustomerSchema },
  create: { method: 'POST' as const, path: '/api/v1/customers' as const, params: CreateCustomersParamsSchema, response: CustomerSchema },
  update: { method: 'PATCH' as const, path: '/api/v1/customers/:id' as const, params: UpdateCustomersParamsSchema, response: CustomerSchema },
  destroy: { method: 'DELETE' as const, path: '/api/v1/customers/:id' as const, params: DestroyCustomersParamsSchema },
} as const;

export const IndexOrdersParamsSchema = z.object({

});

export const ShowOrdersParamsSchema = z.object({
  id: z.uuid(),
});

export const CreateOrdersParamsSchema = z.object({
  customerId: z.uuid(),
  shippingAddress: z.string().optional(),
  items: z.array(OrderItemInputSchema),
});

export const ConfirmOrdersParamsSchema = z.object({
  id: z.uuid(),
});

export const CancelOrdersParamsSchema = z.object({
  id: z.uuid(),
});

export const SearchOrdersParamsSchema = z.object({
  status: OrderStatusSchema.optional(),
  fromDate: z.iso.date().optional(),
  toDate: z.iso.date().optional(),
});

export type CreateOrdersBusinessError = { code: 'validation_failed'; message: string };

export type ConfirmOrdersBusinessError = { code: 'not_found' | 'invalid_transition'; message: string };

export type CancelOrdersBusinessError = { code: 'not_found' | 'invalid_transition'; message: string };

export const OrdersContract = {
  index: { method: 'GET' as const, path: '/api/v1/orders' as const, params: IndexOrdersParamsSchema, response: OrderSchema },
  show: { method: 'GET' as const, path: '/api/v1/orders/:id' as const, params: ShowOrdersParamsSchema, response: OrderSchema },
  create: { method: 'POST' as const, path: '/api/v1/orders' as const, params: CreateOrdersParamsSchema, response: OrderSchema, errors: [{ code: 'validation_failed' as const, status: 422 as const }] as const },
  confirm: { method: 'PATCH' as const, path: '/api/v1/orders/:id/confirm' as const, params: ConfirmOrdersParamsSchema, response: OrderSchema, errors: [{ code: 'not_found' as const, status: 404 as const }, { code: 'invalid_transition' as const, status: 422 as const }] as const },
  cancel: { method: 'PATCH' as const, path: '/api/v1/orders/:id/cancel' as const, params: CancelOrdersParamsSchema, response: OrderSchema, errors: [{ code: 'not_found' as const, status: 404 as const }, { code: 'invalid_transition' as const, status: 422 as const }] as const },
  search: { method: 'GET' as const, path: '/api/v1/orders/search' as const, params: SearchOrdersParamsSchema, response: OrderSchema },
} as const;

export const IndexProductsParamsSchema = z.object({

});

export const ShowProductsParamsSchema = z.object({
  id: z.uuid(),
});

export const CreateProductsParamsSchema = z.object({
  name: z.string().min(1),
  sku: z.string().min(1),
  price: z.number().min(0),
  stock: z.number().int().min(0),
  published: z.boolean().default(false),
});

export const UpdateProductsParamsSchema = z.object({
  id: z.uuid(),
  name: z.string().min(1).optional(),
  sku: z.string().min(1).optional(),
  price: z.number().min(0).optional(),
  stock: z.number().int().min(0).optional(),
  published: z.boolean().optional(),
});

export const DestroyProductsParamsSchema = z.object({
  id: z.uuid(),
});

export const ProductsContract = {
  index: { method: 'GET' as const, path: '/api/v1/products' as const, params: IndexProductsParamsSchema, response: ProductSchema },
  show: { method: 'GET' as const, path: '/api/v1/products/:id' as const, params: ShowProductsParamsSchema, response: ProductSchema },
  create: { method: 'POST' as const, path: '/api/v1/products' as const, params: CreateProductsParamsSchema, response: ProductSchema },
  update: { method: 'PATCH' as const, path: '/api/v1/products/:id' as const, params: UpdateProductsParamsSchema, response: ProductSchema },
  destroy: { method: 'DELETE' as const, path: '/api/v1/products/:id' as const, params: DestroyProductsParamsSchema },
} as const;

export const ShowSettingsParamsSchema = z.object({

});

export const UpdateSettingsParamsSchema = z.object({
  storeName: z.string().min(1).optional(),
  currency: z.string().min(3).max(3).optional(),
  timezone: z.string().optional(),
  maintenanceMode: z.boolean().optional(),
});

export const SettingsContract = {
  show: { method: 'GET' as const, path: '/api/v1/settings/:id' as const, params: ShowSettingsParamsSchema },
  update: { method: 'PATCH' as const, path: '/api/v1/settings/:id' as const, params: UpdateSettingsParamsSchema },
} as const;
