// Auto-generated by Zodra — DO NOT EDIT
export interface Customer {
  id: string;
  name: string;
  email: string;
  phone?: string;
  notes: null | string;
  registeredAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface CustomerSummary {
  id: string;
  name: string;
  email: string;
}

export interface OrderItemInput {
  productId: string;
  quantity: number;
}

export type OrderStatus = 'draft' | 'confirmed' | 'shipped' | 'delivered' | 'cancelled';

export type PaymentMethod =
  | { type: 'card'; lastFour: string; brand: string; expiryMonth: string; expiryYear: string }
  | { type: 'bank_transfer'; bankName: string; accountLastFour: string };

export interface Product {
  id: string;
  name: string;
  sku: string;
  price: number;
  stock: number;
  published: boolean;
}

export interface LineItem {
  id: string;
  product: Product;
  quantity: number;
  unitPrice: number;
  totalPrice: number;
}

export interface Order {
  id: string;
  number: string;
  status: OrderStatus;
  customer: Customer;
  lineItems: LineItem[];
  paymentMethod: PaymentMethod;
  totalAmount: number;
  shippingAddress?: string;
  estimatedDelivery: null | string;
  createdAt: string;
  updatedAt: string;
}

export interface IndexCustomersParams {

}

export interface ShowCustomersParams {
  id: string;
}

export interface CreateCustomersParams {
  name: string;
  email: string;
  phone?: string;
  notes: null | string;
}

export interface UpdateCustomersParams {
  name?: string;
  email?: string;
  phone?: string;
  notes?: null | string;
}

export interface DestroyCustomersParams {
  id: string;
}

export interface CustomersContract {
  index: { method: 'GET'; path: '/customers'; params: IndexCustomersParams; response: CustomerSummary; collection: true };
  show: { method: 'GET'; path: '/customers/:id'; params: ShowCustomersParams; response: Customer };
  create: { method: 'POST'; path: '/customers'; params: CreateCustomersParams; response: Customer };
  update: { method: 'PATCH'; path: '/customers/:id'; params: UpdateCustomersParams; response: Customer };
  destroy: { method: 'DELETE'; path: '/customers/:id'; params: DestroyCustomersParams };
}

export interface IndexOrdersParams {

}

export interface ShowOrdersParams {
  id: string;
}

export interface CreateOrdersParams {
  customerId: string;
  shippingAddress?: string;
  items: OrderItemInput[];
}

export interface ConfirmOrdersParams {
  id: string;
}

export interface CancelOrdersParams {
  id: string;
}

export interface SearchOrdersParams {
  status?: OrderStatus;
  fromDate?: string;
  toDate?: string;
}

export interface OrdersContract {
  index: { method: 'GET'; path: '/orders'; params: IndexOrdersParams; response: Order; collection: true };
  show: { method: 'GET'; path: '/orders/:id'; params: ShowOrdersParams; response: Order };
  create: { method: 'POST'; path: '/orders'; params: CreateOrdersParams; response: Order };
  confirm: { method: 'PATCH'; path: '/orders/:id/confirm'; params: ConfirmOrdersParams; response: Order };
  cancel: { method: 'PATCH'; path: '/orders/:id/cancel'; params: CancelOrdersParams; response: Order };
  search: { method: 'GET'; path: '/orders/search'; params: SearchOrdersParams; response: Order; collection: true };
}

export interface IndexProductsParams {

}

export interface ShowProductsParams {
  id: string;
}

export interface CreateProductsParams {
  name: string;
  sku: string;
  price: number;
  stock: number;
  published: boolean;
}

export interface UpdateProductsParams {
  id: string;
  name?: string;
  sku?: string;
  price?: number;
  stock?: number;
  published?: boolean;
}

export interface DestroyProductsParams {
  id: string;
}

export interface ProductsContract {
  index: { method: 'GET'; path: '/products'; params: IndexProductsParams; response: Product; collection: true };
  show: { method: 'GET'; path: '/products/:id'; params: ShowProductsParams; response: Product };
  create: { method: 'POST'; path: '/products'; params: CreateProductsParams; response: Product };
  update: { method: 'PATCH'; path: '/products/:id'; params: UpdateProductsParams; response: Product };
  destroy: { method: 'DELETE'; path: '/products/:id'; params: DestroyProductsParams };
}

export interface ShowSettingsParams {

}

export interface UpdateSettingsParams {
  storeName?: string;
  currency?: string;
  timezone?: string;
  maintenanceMode?: boolean;
}

export interface SettingsContract {
  show: { method: 'GET'; path: '/settings/:id'; params: ShowSettingsParams };
  update: { method: 'PATCH'; path: '/settings/:id'; params: UpdateSettingsParams };
}
